### ISSUE TITLE
Respawn mechanic balancing

### ISSUE THREAD

**Issue by StargateMC** [OneDayStudios/StargateMC-Project#13]
At present the respawn mechanics allow players to explore the galaxy they died in (or the nearest one) by repeatedly killing themselves.

This change proposes;

**For Players out of range or without a home:**

- [x] Players will respawn at the spawn location for the world they died on if it is Temperate, Oceanic or Tropical, provided the spawn location of that world is on a land mass, the world is not NPC controlled and the world has an atmosphere.
- [x] Players will spawn on a random temperate world with an atmosphere in the nearest galaxy to their death location if the above criteria are not met. 
`Note it is not possible to check for a spawn point in the ocean in this case but it is highly unlikely land will be far away.`

**For Players in range and with a home:**

- [x] They will respawn at their home location.

**Comment by Destiny3378** [comment]
Players will spawn on a random temperate world with an atmosphere in the nearest galaxy to their death location if the above criteria are not met.

does not work correctly i do not get put to the nearest galaxy i get shot to 0 cluster
