### ISSUE TITLE
Respawn mechanic still glitched

### ISSUE THREAD

**Issue by Destiny3378** [OneDayStudios/StargateMC-Project#16]
so the respawn mechanic is still glitched to where if you die in space outside of home cluster you get shot to VH49XJ0V0 and it also happened when I was flying low (like y=0) it teleported me to that same planet oddly enough and then it loaded me I entered atmosphere and then it killed me?!
anyway I assume you can figure out how to repeat based off this but if not

1. go to any other cluster
2. fly low in space/die
3. wait for what comes next

**Comment by StargateMC** [comment]
I'm going to make it so that the default spawn point in the event of any issues will be a random habitable location near you.

**Comment by StargateMC** [comment]
I haven't been able to reproduce this in the past month.
Please confirm you cannot either.
