### ISSUE TITLE
Add-on Suggestion

### ISSUE THREAD

**Issue by Destiny3378** [OneDayStudios/StargateMC-Project#17]
- [ ] HandHeld Gate Power source for IG/IC dialing from any gate

- [ ] HandHeld DHD (i think this is already on the table but if its not then here it is)

- [ ] SubSpace Capacitor (for the stargate atlantis episode where the Dedalus travels through realities 

- [ ] Project Arcturus machine type: Project Arcturus was an attempt by the Ancients to extract Zero point energy from their own universe, with the ultimate goal of replacing the Zero Point Modules.

- [ ] Naquadria
- [ ] Naquadria Generators
- [ ] Larger Capacity for the IC2 Stargate Power Units (A capacity that is equal to the enhanced ZPM or teir right before)

**Comment by StargateMC** [comment]
Hi Joey,

Please open seperate issues for each request.

The last option will not happen though, sorry mate.

Cheers,

Byso

**Comment by Destiny3378** [comment]
ight i will make separate ones soon
